const INDEX_PATH='data/soloviev_test_index_v5.json';
const state={index:null,questions:[],current:0,answers:[]};
const $=id=>document.getElementById(id);
function clean(s){return String(s??'').replace(/\u00ad/g,'').replace(/\u0018/g,'').replace(/\uf0b7/g,' ').replace(/\s+/g,' ').trim()}
function words(s){return clean(s).toLowerCase().match(/[а-яёa-z0-9]{3,}/g)||[]}
const STOP=new Set('и в во на за по из к ко от до для с со у о об при не ни что это как так же если то чем где когда который которая которые которое быть был была были является можно нужно их его ее они мы вы нас вам мне меня уже еще только очень более менее также потому поэтому однако таким образом между через после перед над под при этом поскольку чтобы либо ли бы вот здесь там тогда далее теперь данный данная данные данной этого этой такой такая такие свое свои свою которых которые'.split(' '));
function stem(w){let x=w.toLowerCase();if(x.length<=5)return x;return x.replace(/(иями|ами|ями|ого|ему|ому|ими|ыми|ее|ие|ые|ой|ий|ый|ая|яя|ое|ем|им|ым|ом|ах|ях|ов|ев|ей|ам|ям|ум|ию|ью|ия|ья|ие|ье|у|ю|а|я|ы|и|е|о)$/,'').slice(0,12)}
function keyset(s){return new Set(words(s).filter(w=>!STOP.has(w)).map(stem))}
function overlap(a,b){const A=keyset(a),B=keyset(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>{if(B.has(x))n++});return n/Math.max(1,A.size)}
function theory(sec){return Array.isArray(sec.theory)?sec.theory.map(clean).filter(x=>x.length>=35):[]}
function validConcept(c){return c&&clean(c.name).length>=3&&clean(c.definition).length>=45&&!/пример|задач|решени|excel|ячейк/i.test(c.definition)}
function validFormula(f){const x=clean(f?.formula);return !!f&&x.length>=5&&!/пример|задач|решени|excel|ячейк|табл\.|рис\./i.test(x)&&(/[=≤≥∑√]/.test(x)||/[A-ZА-ЯЁ]ₙ/.test(x))}
function localContext(sec,text){const a=theory(sec),i=a.indexOf(text);if(i<0)return text;return a.slice(Math.max(0,i-1),Math.min(a.length,i+2)).join(' ')}
function add(out,q,expected,reference,keys,type,sec){out.push({type,question:q,expected:clean(expected),reference:clean(reference),keys:[...new Set(keys.filter(Boolean))].slice(0,12),section:sec})}
function makeQuestions(sec){
 const out=[],cs=(sec.concepts||[]).filter(validConcept),fs=(sec.formulas||[]).filter(validFormula),ms=(sec.methods||[]).filter(m=>m&&clean(m.description).length>=55&&!/пример|задач|решени|excel|ячейк/i.test(m.description)),ts=theory(sec);
 cs.forEach(c=>{const name=clean(c.name),def=clean(c.definition);add(out,`Что в учебнике называется «${name}»? Дайте определение и укажите отличительный признак, приведённый в определении.`,def,def,words(name).map(stem),'definition',sec);add(out,`Какими свойствами или признаками характеризуется «${name}» согласно определению в теме?`,def,def,words(def).filter(w=>!STOP.has(w)).map(stem),'definition',sec)});
 fs.forEach(f=>{const name=clean(f.name||'формулу'),formula=clean(f.formula),exp=clean(f.explanation||'');add(out,`Запишите ${name}. Объясните, что обозначают основные элементы формулы и при каких условиях она применяется.`,`${formula}. ${exp}`,`${formula}. ${exp}`,words(name+' '+exp).map(stem),'formula',sec);add(out,`Какую формулу для «${name}» приводит учебник? Запишите её и объясните смысл результата.`,`${formula}. ${exp}`,`${formula}. ${exp}`,words(name+' '+exp).map(stem),'formula',sec)});
 ms.forEach(m=>add(out,`Каков основной порядок действий/назначение «${clean(m.name||sec.title)}», описанный в теории? Назовите конкретные действия или условия.`,m.description,m.description,words(m.description).filter(w=>!STOP.has(w)).map(stem),'method',sec));
 ts.forEach((t,i)=>{const low=t.toLowerCase();if(/называется|называются|называют/.test(low)){const m=t.match(/(?:что\s+)?([^,.;:]{3,100})\s+(?:называется|называются|называют)\s+(.+)/i);if(m){add(out,`Что называется «${clean(m[1])}»? Сформулируйте определение из учебника.`,t,t,words(m[1]).map(stem),'theory',sec);return}}if(/первым шагом|первый шаг/.test(low))add(out,`Каков первый шаг при ${low.includes('поиск')?'поиске':'выполнении'} описанной в теме процедуры? Укажите его точно по теории.`,t,t,words(t).filter(w=>!STOP.has(w)).map(stem),'theory',sec);else if(/вариант|следующие|способ(а|ы)|случа(е|ях)|услови/.test(low))add(out,`Какие конкретные варианты или условия работы с объектом рассматриваются в этой теме? Перечислите их.`,t,t,words(t).filter(w=>!STOP.has(w)).map(stem),'theory',sec);else if(/отлича|различа|равно|равна|равны|определя|вычисля|выража/.test(low))add(out,`Какое конкретное соотношение, различие или правило сформулировано в этом фрагменте теории? Запишите его и поясните.`,t,t,words(t).filter(w=>!STOP.has(w)).map(stem),'theory',sec);else if(i<8)add(out,`Какой конкретный факт или правило приведено в учебнике по теме «${clean(sec.title)}» в этом фрагменте? Сформулируйте его своими словами.`,t,localContext(sec,t),words(t).filter(w=>!STOP.has(w)).map(stem),'theory',sec)});
 const uniq=[],seen=new Set();for(const q of out){const k=q.question.toLowerCase();if(!seen.has(k)){seen.add(k);uniq.push(q)}}return uniq;
}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function generate(sec,n){const pool=makeQuestions(sec);return shuffle(pool).slice(0,Math.min(n,pool.length))}
function evaluate(answer,q){const a=clean(answer);if(!a)return{score:0,label:'Ответ не введён',cls:'partial'};const A=keyset(a),C=keyset(q.expected||q.reference||'');const expectedWords=[...C].filter(x=>x.length>=4);let matched=0;expectedWords.forEach(x=>{if(A.has(x))matched++});const coverage=expectedWords.length?matched/expectedWords.length:0;const named=(q.keys||[]).filter(x=>A.has(x)).length,namedCoverage=q.keys?.length?named/q.keys.length:0;const sim=overlap(a,q.expected||q.reference||''),qsim=overlap(a,q.question);let score=Math.max(coverage*1.45,namedCoverage*1.2,sim*1.05);score-=Math.min(.45,qsim*.7);if(words(a).length<3)score-=.15;score=Math.max(0,Math.min(1,score));let label='Не зачтено',cls='bad';if(score>=.55){label='Зачтено';cls='good'}else if(score>=.30){label='Частично';cls='partial'}return{score,label,cls,matched,total:expectedWords.length,context:q.expected||q.reference||''}}
function renderQuestion(){const q=state.questions[state.current];if(!q)return;$('qmeta').textContent=`Вопрос ${state.current+1} из ${state.questions.length} · ${q.section.id} ${q.section.title}`;$('question').textContent=q.question;$('answer').value='';$('feedback').innerHTML='';$('reference').classList.add('hidden');$('next').disabled=false;$('check').disabled=false}
async function loadIndex(){try{const r=await fetch(INDEX_PATH,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.index=await r.json();const secs=Array.isArray(state.index.sections)?state.index.sections:[];if(!secs.length)throw new Error('В индексе нет разделов');const select=$('topic');select.innerHTML='';secs.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${s.id||''} ${s.title||''}`.trim();select.appendChild(o)});$('topic').disabled=false;$('start').disabled=false;$('status').textContent=`Индекс ${state.index.version||''} загружен: ${state.index.source||'учебник Соловьева'}. Разделов: ${secs.length}.`;}catch(e){$('status').innerHTML=`<strong>Не удалось загрузить индекс.</strong><br>Проверьте путь <code>${INDEX_PATH}</code> и публикацию GitHub Pages.<br><small>${clean(e.message)}</small>`}}
$('start').onclick=()=>{const sec=state.index.sections[Number($('topic').value)];state.questions=generate(sec,Number($('count').value));state.current=0;state.answers=[];if(!state.questions.length){$('status').textContent='Для выбранной темы не найдено достаточно конкретного материала.';return}$('test').classList.remove('hidden');$('resultCard').classList.add('hidden');renderQuestion();window.scrollTo({top:$('test').offsetTop-20,behavior:'smooth'})};
$('check').onclick=()=>{const q=state.questions[state.current],result=evaluate($('answer').value,q);if(!clean($('answer').value)){$('feedback').innerHTML=`<div class="feedback partial"><strong>${result.label}.</strong><br>Можно перейти к следующему вопросу без проверки.</div>`;return}state.answers[state.current]=result.score;$('feedback').innerHTML=`<div class="feedback ${result.cls}"><div class="score">${Math.round(result.score*100)}%</div><strong>${result.label}</strong><br>Проверка выполнена по содержанию конкретного теоретического фрагмента, понятия или формулы, относящихся к этому вопросу.</div>`;$('reference').innerHTML=`<strong>Основа проверки:</strong><br><br>${clean(result.context).slice(0,3000)}`;$('reference').classList.remove('hidden')};
$('next').onclick=()=>{if(state.current+1>=state.questions.length){const checked=state.answers.filter(x=>typeof x==='number'),avg=checked.length?checked.reduce((a,b)=>a+b,0)/checked.length:0;$('test').classList.add('hidden');$('resultCard').classList.remove('hidden');$('result').innerHTML=`<div class="score">${checked.length?Math.round(avg*100)+'%':'—'}</div><p>Проверено ответов: ${checked.length} из ${state.questions.length}. Пропущенные вопросы не считаются ошибкой.</p>`;window.scrollTo({top:$('resultCard').offsetTop-20,behavior:'smooth'});return}state.current++;renderQuestion()};
$('restart').onclick=()=>{$('resultCard').classList.add('hidden');$('test').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})};
loadIndex();
