const state={index:null,questions:[],current:0,answers:[]};
const $=id=>document.getElementById(id);
function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}
function words(s){return clean(s).toLowerCase().match(/[а-яёa-z0-9]{3,}/g)||[]}
const stop=new Set('и в во на за по из к ко от до для с со у о об при не ни что это как так же если то чем где когда который которая которые которое быть был была были является можно нужно их его ее они мы вы нас вам мне меня уже еще только очень более менее также потому поэтому однако таким образом между через после перед над под при этом поскольку чтобы либо ли бы вот здесь там тогда далее теперь затем'.split(' '));
function keyset(s){return new Set(words(s).filter(x=>!stop.has(x)))}
function similarity(a,b){const A=keyset(a),B=keyset(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>{if(B.has(x))n++});return n/Math.max(1,A.size)}
function sectionSentences(sec){if(Array.isArray(state.index.sentences)){const a=sec.start_page||1,b=sec.end_page||99999;const x=state.index.sentences.filter(s=>s.page>=a&&s.page<=b);if(x.length)return x}return clean(sec.text).split(/(?<=[.!?])\s+/).filter(x=>x.length>=50).map(text=>({text,page:sec.start_page}))}
function makeQuestion(term,ref,sec){const low=ref.toLowerCase();let q;if(/\bэто\b|называется|определяется|понимается|представляет собой|означает/.test(low))q=`Что такое «${term}»? Дайте определение и укажите основные признаки.`;else if(/делится|виды|типы|классифиц|групп|различают/.test(low))q=`Какие основные виды или группы связаны с понятием «${term}»? Охарактеризуйте их.`;else if(/метод|алгоритм|этап|последовательн|процедур/.test(low))q=`В чем состоит метод или процедура, связанная с понятием «${term}»? Назовите основные этапы.`;else if(/формул|рассчит|вычисл|показател|коэффициент/.test(low))q=`Как используется «${term}» при анализе данных? Укажите способ расчёта и объясните обозначения.`;else q=`Какова роль понятия «${term}» в теме «${sec.title}»? Раскройте содержание и приведите существенные характеристики.`;return {question:q,reference:ref,must:[term],section:sec}}
function generate(sec,n){let ss=sectionSentences(sec),candidates=[];for(const s of ss){const text=clean(s.text);if(text.length<70||text.length>650)continue;for(const t of keyset(text)){if(t.length>=5)candidates.push({term:t,ref:text,page:s.page})}}candidates.sort((a,b)=>b.ref.length-a.ref.length);const used=new Set(),out=[];for(const c of candidates){if(out.length>=n)break;if(used.has(c.term))continue;used.add(c.term);out.push(makeQuestion(c.term,c.ref,sec))}return out}
function renderQuestion(){const q=state.questions[state.current];if(!q)return;const total=state.questions.length;$('qmeta').textContent=`Вопрос ${state.current+1} из ${total} · Тема: ${q.section.title}`;$('question').textContent=q.question;$('answer').value='';$('feedback').innerHTML='';$('reference').classList.add('hidden');$('next').disabled=true;$('check').disabled=false}
function evaluate(answer,q){const context=[q.reference,...sectionSentences(q.section).map(x=>x.text)].join(' ').slice(0,9000);const sim=similarity(answer,context);const coverage=q.must.filter(t=>keyset(answer).has(t.toLowerCase())).length/q.must.length;const len=words(answer).length;let score=Math.max(sim,coverage*.9);if(len<10)score*=.55;else if(len<20)score*=.8;let cls='bad',label='Не зачтено';if(score>=.55){cls='good';label='Зачтено'}else if(score>=.35){cls='partial';label='Частично'}return{score:Math.min(1,score),len,label,cls,context}}
async function loadIndex(){try{const r=await fetch('data/book_index.json',{cache:'no-store'});if(!r.ok)throw new Error('Файл data/book_index.json не найден');state.index=await r.json();const secs=state.index.sections||[];const select=$('topic');select.innerHTML='';secs.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${s.id||''} ${s.title}`.trim();select.appendChild(o)});if(secs.length){$('topic').disabled=false;$('start').disabled=false;$('status').textContent=`Учебник загружен: ${state.index.source||'индексированный учебник'}. Тем из оглавления: ${secs.length}.`;}else throw new Error('В индексе нет разделов.')}catch(e){$('status').innerHTML=`<strong>Ошибка загрузки индекса:</strong> ${e.message}. Файл должен находиться по пути data/book_index.json.`}}
$('start').onclick=()=>{const sec=state.index.sections[Number($('topic').value)];state.questions=generate(sec,Number($('count').value));state.current=0;state.answers=[];if(!state.questions.length){$('status').textContent='Для выбранной темы не удалось сформировать вопросы.';return}$('test').classList.remove('hidden');$('resultCard').classList.add('hidden');renderQuestion();window.scrollTo({top:$('test').offsetTop-20,behavior:'smooth'})};
$('check').onclick=()=>{const ans=$('answer').value.trim();if(words(ans).length<3){$('feedback').innerHTML='<div class="feedback bad"><strong>Ответ слишком короткий.</strong><br>Напишите развёрнутый ответ: желательно не менее 30 слов.</div>';return}const r=evaluate(ans,state.questions[state.current]);state.answers[state.current]=r.score;$('feedback').innerHTML=`<div class="feedback ${r.cls}"><div class="score">${Math.round(r.score*100)}%</div><strong>${r.label}</strong><br>Объём ответа: ${r.len} слов.<br><br>Оценка основана на ключевых понятиях и содержательном контексте выбранной темы.</div>`;$('reference').innerHTML=`<strong>Фрагмент материала, использованный для диагностики:</strong><br><br>${r.context.slice(0,2500)}`;$('reference').classList.remove('hidden');$('next').disabled=false;$('check').disabled=true};
$('next').onclick=()=>{if(state.current+1>=state.questions.length){const a=state.answers.filter(x=>typeof x==='number');const avg=a.length?a.reduce((x,y)=>x+y,0)/a.length:0;$('test').classList.add('hidden');$('resultCard').classList.remove('hidden');$('result').innerHTML=`<div class="score">${Math.round(avg*100)}%</div><p>Проверено ответов: ${a.length} из ${state.questions.length}.</p>`;window.scrollTo({top:$('resultCard').offsetTop-20,behavior:'smooth'});return}state.current++;renderQuestion()};
$('restart').onclick=()=>{$('resultCard').classList.add('hidden');$('test').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})};
loadIndex();
